clc
clear
%% 
load("ill-casey0.mat")
tol = 1e-5;
%% 
% opf.violation is used as setter for h
% fmincon.tol_x is used as setter for rtol
% fmincon.tol_f is used as setter for atol
% mips.max_it for fac2
% mips.step_control for step size control
% mips.sc.red_it for sarm type
mpoptli = mpoption('pf.alg', 'sicnm', 'verbose', 3,'out.all',0, ...
    'pf.nr.max_it', 500, 'opf.violation', 5,...
    'fmincon.tol_x', 1e-1,...
    'fmincon.tol_f', 1e-1, ...
    'mips.sc.red_it',2, ...
    'mips.max_it',6.0,...
    'mips.step_control',1, ...
    'pf.tol', tol); 
pf_rodas3d=runpfa(scenario, mpoptli);
mpoptli = mpoption('pf.alg', 'sicnm', 'verbose', 3,'out.all',0, ...
    'pf.nr.max_it', 500, 'opf.violation', 5,...
    'fmincon.tol_x', 1e-1,...
    'fmincon.tol_f', 1e-1, ...
    'mips.sc.red_it',1, ...
    'mips.max_it',6.0,...
    'mips.step_control',1, ...
    'pf.tol', tol); 
pf_rodas4=runpfa(scenario, mpoptli);
%% cnm
% mips.sc.red_it for cnm type
% opf.violation is used as setter for h
% mips.max_it for maximum inner loop iteration
% ICNM-JH
mpoptcnm = mpoption('pf.alg','cnm','verbose', 3,'out.all',0,'opf.start',1, ...
    'opf.violation', 1e-2,'pf.nr.max_it', 500,...
    'mips.max_it', 30,...
    'mips.sc.red_it', 1, ...
    'pf.tol', tol);
pficnmjh=runpfa(scenario, mpoptcnm);
% ICNM-J
mpoptcnm = mpoption('pf.alg','cnm','verbose', 3,'out.all',0,'opf.start',1, ...
    'opf.violation', 1e-2,'pf.nr.max_it', 1000,...
    'mips.max_it', 30, ...
    'mips.sc.red_it', 2, ...
    'pf.tol', tol);
pficnmj=runpfa(scenario, mpoptcnm);
% ICNM-J1
mpoptcnm = mpoption('pf.alg','cnm','verbose', 3,'out.all',0,'opf.start',1, ...
    'opf.violation', 1e-2,'pf.nr.max_it', 1000,...
    'mips.max_it', 30, ...
    'mips.sc.red_it', 3, ...
    'pf.tol', tol);
pficnmj1=runpfa(scenario, mpoptcnm);
% ICNM-J0
mpoptcnm = mpoption('pf.alg','cnm','verbose', 3,'out.all',0,'opf.start',1, ...
    'opf.violation', 1e-2,'pf.nr.max_it', 1000,...
    'mips.max_it', 30, ...
    'mips.sc.red_it', 4, ...
    'pf.tol', tol);
pficnmj0=runpfa(scenario, mpoptcnm);
% CNM-ERK4
mpoptcnm = mpoption('pf.alg','cnm','verbose', 3,'out.all',0,'opf.start',1, ...
    'opf.violation', 1e-2,'pf.nr.max_it', 1000,...
    'mips.max_it', 30, ...
    'mips.sc.red_it',5, ...
    'pf.tol', tol);
pfecnm=runpfa(scenario, mpoptcnm);
%% 2S4
mpoptli = mpoption('pf.alg', '2S4', 'verbose', 3,'out.all',0, 'pf.nr.max_it', 500, ...
    'pf.tol', tol); 
pf_2s4=runpfa(scenario, mpoptli);
%% IWAMOTO
mpoptli = mpoption('pf.alg', 'IWAMOTO', 'verbose', 3,'out.all',0, 'pf.nr.max_it', 500, ...
    'pf.tol', tol); 
pf_iwamoto=runpfa(scenario, mpoptli);
%% MANN
mpoptli = mpoption('pf.alg', 'MANN', 'verbose', 3,'out.all',0, 'pf.nr.max_it', 1000, ...
    'pf.tol', tol); 
pf_mann=runpfa(scenario, mpoptli);
%% ROMBERG
mpoptli = mpoption('pf.alg', 'ROMBERG', 'verbose', 3,'out.all',0, 'pf.nr.max_it', 500, ...
    'pf.tol', tol); 
pf_romberg=runpfa(scenario, mpoptli);
%% NR
mpoptnr = mpoption('verbose', 3,'out.all',0,'opf.start',1, 'pf.nr.max_it', 500, ...
    'pf.tol', tol); 
pf2=runpf(scenario, mpoptnr);
